version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks: [laranet]

  web:
    image: nginx:alpine
    container_name: laravel_web
    depends_on: [app]
    ports:
      - "8000:80"   # visit http://localhost:8000
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: [laranet]

  # Uncomment if you actually need MySQL
  # db:
  #   image: mysql:8
  #   container_name: laravel_db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: laravel
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   networks: [laranet]

networks:
  laranet:

volumes:
  dbdata:
